### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by ham-cap** [ham-cap/flip-phrases#25]

**Comment by ham-cap** [comment]
![image](https://github.com/user-attachments/assets/f929f5fb-7be6-4104-b4f1-8fd9c895e194)

**Comment by yoshitsugu** [comment]
- `memorized` はたとえば `memorized_at` などで日時を保存しておくと、今後もし「覚えて3ヶ月たったら再度表示する」という機能を実装したくなったときに便利かなと思いました。
- `ja_phrase` と `en_phrase` の重複についてはどう考えますか？両方の組み合わせとして重複を許さない、片方だけ見て重複を許さない、重複を許す、くらいのパターンがあるかなと思います。

**Comment by ham-cap** [comment]
@yoshitsugu 
> memorized はたとえば memorized_at などで日時を保存しておくと、今後もし「覚えて3ヶ月たったら再度表示する」という機能を実装したくなったときに便利かなと思いました。

ここは考えられていなかったです👀
ありがとうございます！
日時の保存もするようにします🙆‍♂️
修正したものを上のコメントに追記しておりますのでご確認お願いいたします🙇‍♂️

重複についてですが、基本的に「各カラム内での重複は許すが、組み合わせとしては重複を許さない」というスタンスで考えています。
というのも、このサービスを単語帳として使用する場合、全く同じスペルで異なる意味を持つ単語を許容する必要があるからです。
例えば、`minute`という単語は時間の「分」を表す名詞以外にも、全く同じスペルで「微笑な」という意味の形容詞もあり、発音記号や文脈なしで見分けることができません。
カラムごとにユニーク制約を付けてしまうと、このサービス上ではいずれかしか登録できないことになってしまうので、各カラム内においては重複が発生する前提で考えています。
日本語においては英語ほどではないかもしれませんが、「はし」＝「箸」or「橋」といった例もあるので、こちらも重複を許容する必要があると思います。
ただし、同じ組み合わせのカードが複数存在する意味はないので、そこの重複は許さないのがよいと思います。
したがって、冒頭で書いたように「各カラム内での重複はOK。`ja_phrase`と`en_phrase`の組み合わせは重複NG。」という形で考えているのですが、いかがでしょうか？👀

なお、このサービスは単語帳としてだけでなく、1~2センテンスぐらいの短文を丸ごとカードにして音読素材などとして活用してもらうことも想定しています。
そういった使い方の場合、意味は同じでも「てにおは」や句読点の有無等が少しだけ異なっているというカードも存在し得るので、厳密に重複チェックをするのは難しいとも思うのですが、単語帳としての使い方を想定した上記の制約を設けることを妨げるものではないと考えています。

**Comment by yoshitsugu** [comment]
- `memorized_at` をNULL許容にしておけば、 `memorized_at` があれば覚えたということにする、というロジックで `memorized` の代用になると思います。どうでしょうか。
- 重複について、考え方は理解しました。実際の実装についてですが、 `ja_phrase` と`en_phrase` は `text` 型のような長文を想定したデータ型になるかと思います。その場合、DBではユニークインデックスの設定がやや難しいです。あまり重複自体発生しない想定で、アプリケーション側のバリデーションだけで行うことにしてもいいかもしれませんね。

**Comment by ham-cap** [comment]
@yoshitsugu 

> memorized_at をNULL許容にしておけば、 memorized_at があれば覚えたということにする、というロジックで memorized の代用になると思います。どうでしょうか。

なるほどです👀
修正しました🙌

> あまり重複自体発生しない想定で、アプリケーション側のバリデーションだけで行うことにしてもいいかもしれませんね。

そうですね。
このサービスが想定している使い方であれば重複が起きることのほうが稀だと思うので、おっしゃる通りアプリケーション側でのバリデーションのみで考えたいと思います。
後学のために教えていただきたいのですが、DBでは特に制約を設けずにアプリケーション側のバリデーションだけで運用するというのは実際の業務でもよくあることなのでしょうか？👀
自分の中でDB側の制約とアプリケーション側のバリデーションはセットで設定するのが原則という刷り込みのようなものがあって、よほどの理由がなければどちらか一方での運用というのはしないものなんだと思い込んでいたのですが、割と柔軟に対応する例も多そうな雰囲気を今回感じたのでお伺いしたいなと思った次第です🙏

**Comment by yoshitsugu** [comment]
> 後学のために教えていただきたいのですが、DBでは特に制約を設けずにアプリケーション側のバリデーションだけで運用するというのは実際の業務でもよくあることなのでしょうか？👀
> 自分の中でDB側の制約とアプリケーション側のバリデーションはセットで設定するのが原則という刷り込みのようなものがあって、よほどの理由がなければどちらか一方での運用というのはしないものなんだと思い込んでいたのですが、割と柔軟に対応する例も多そうな雰囲気を今回感じたのでお伺いしたいなと思った次第です🙏

基本DBの制約とアプリケーションのバリデーションはそろえたほうが無難です。
今回のようにそうすると実装コストがかかる場合はコストと利点のバランスを考えて判断することが多いです。

**Comment by ham-cap** [comment]
@yoshitsugu 
なるほど

**Comment by yoshitsugu** [comment]
こちらもOKとします！
